apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: vinipachecov/multi-client
      context: client
      docker:
        dockerfile: dev.Dockerfile
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
deploy:
  kubectl:
    manifests:
     - k8s/client-deployment.yaml
    