apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: vinipachecov/multi-client
      context: client
      docker:
        dockerfile: dev.Dockerfile
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: viniapchecov/multi-server
      context: server
      docker:
        dockerfile: dev.Dockerfile
      sync:
        '**/*.js': .
deploy:
  kubectl:
    manifests:
     - k8s/client-deployment.yaml
     - k8s/server-deployment.yaml
     - k8s/worker-deployment.yaml
     - k8s/server-cluster-ip-service.yaml
     - k8s/client-cluster-ip-service.yaml
    