apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: vinipachecov-online-tls
spec:
  secretName: vinipachecov-online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vinipachecov.online
  dnsNames:
    - vinipachecov.online
    - www.vinipachecov.online
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - vinipachecov.online
          - www.vinipachecov.online