apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
      requests:
        storage: 2Gi
  # StorageClassName for storage providers in the cloud.