apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingress-service
    # higher level config for ingress
    annotations:
      kubernetes.io/ingress.class: nginx
      # tells how to handle traffic request urls rewrites
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
      - vinipachecov.online
      - www.vinipachecov.online
    secretName: vinipachecov-online
  rules:
    - host: vinipachecov.online
      http:
        paths:
            - path: /?(.*)
              backend:
                serviceName: client-cluster-ip-service
                servicePort: 3000
            - path: /api/?(.*)
              backend:
                  serviceName: server-cluster-ip-service
                  servicePort: 5000
    - host: www.vinipachecov.online 
      http:
        paths:
            - path: /?(.*)
              backend:
                serviceName: client-cluster-ip-service
                servicePort: 3000
            - path: /api/?(.*)
              backend:
                  serviceName: server-cluster-ip-service
                  servicePort: 5000